### ISSUE TITLE
Crash: Unexpected error

### ISSUE THREAD

**Issue by dmodoomsirius** [BBM-Modpacks/Voltz-Configs#10]
[![YAMPST - Open source mod pack statistics tracker](http://files.yampst.net/static/banner-small.png)](https://yampst.net/)

Crash report collection powered by [YAMPST](https://yampst.net/).
### Environment data:

| Key | Value |
| --- | --- |
| Mod pack version | 4.0.11 |
| Minecraft version | 1.7.10 |
| Side | Client side |
### Comments by pack administrator:

_No comments._
### Full crash report:

```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 02.07.2015 16:58
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at net.techbrew.journeymap.model.MapState.setMapType(MapState.java:116)
    at net.techbrew.journeymap.forgehandler.KeyEventHandler.onKeypress(KeyEventHandler.java:104)
    at net.techbrew.journeymap.forgehandler.KeyEventHandler.onKeyboardEvent(KeyEventHandler.java:171)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_648_KeyEventHandler_onKeyboardEvent_KeyInputEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:540)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1861)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.techbrew.journeymap.model.MapState.setMapType(MapState.java:116)
    at net.techbrew.journeymap.forgehandler.KeyEventHandler.onKeypress(KeyEventHandler.java:104)
    at net.techbrew.journeymap.forgehandler.KeyEventHandler.onKeyboardEvent(KeyEventHandler.java:171)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_648_KeyEventHandler_onKeyboardEvent_KeyInputEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:540)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['iysc'/383, l='MpServer', x=-1,30, y=5,62, z=143,91]]
    Chunk stats: MultiplayerChunkCache: 568, 568
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (76,4,-43), Chunk: (at 12,0,5 in 4,-3; contains blocks 64,0,-48 to 79,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Level time: 12634 game time, 12634 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 124 total; [EntityItem['item.item.slimeball'/58131, l='MpServer', x=23,19, y=4,13, z=155,31], EntitySlime['Slime'/44565, l='MpServer', x=-44,49, y=4,47, z=214,79], EntitySlime['Slime'/57122, l='MpServer', x=29,97, y=4,00, z=152,73], EntitySlime['Slime'/36, l='MpServer', x=-83,06, y=5,00, z=99,78], EntitySlime['Slime'/37, l='MpServer', x=-68,51, y=4,00, z=112,44], EntitySlime['Slime'/38, l='MpServer', x=-6,93, y=4,00, z=122,18], EntitySkeleton['Skeleton'/13102, l='MpServer', x=-22,72, y=4,00, z=161,78], EntityItem['item.item.slimeball'/58168, l='MpServer', x=24,50, y=4,13, z=154,19], EntitySlime['Slime'/64, l='MpServer', x=-65,91, y=4,00, z=130,78], EntitySkeleton['Skeleton'/65, l='MpServer', x=-23,53, y=5,00, z=152,06], EntityBat['Bat'/66, l='MpServer', x=-23,75, y=6,10, z=154,81], EntityCreeper['Creeper'/67, l='MpServer', x=-26,50, y=4,00, z=155,59], EntityCreeper['Creeper'/68, l='MpServer', x=-31,25, y=4,00, z=155,91], EntityBat['Bat'/69, l='MpServer', x=-20,40, y=12,71, z=138,05], EntitySlime['Slime'/48205, l='MpServer', x=31,13, y=4,00, z=190,63], EntityItem['item.item.slimeball'/48983, l='MpServer', x=15,03, y=4,13, z=147,16], EntitySlime['Slime'/94, l='MpServer', x=23,84, y=4,00, z=74,41], EntityItem['item.item.potato'/95, l='MpServer', x=-2,13, y=5,13, z=122,81], EntityItem['item.item.potato'/96, l='MpServer', x=-3,59, y=5,13, z=123,38], EntityItem['item.item.slimeball'/59488, l='MpServer', x=19,32, y=4,13, z=148,11], EntityItem['item.item.carrots'/97, l='MpServer', x=-4,47, y=5,13, z=125,88], EntitySlime['Slime'/16993, l='MpServer', x=52,53, y=4,00, z=215,56], EntityItem['item.item.potato'/98, l='MpServer', x=-0,56, y=5,13, z=122,88], EntityItem['item.item.carrots'/99, l='MpServer', x=-1,13, y=5,13, z=127,81], EntityBat['Bat'/100, l='MpServer', x=5,48, y=9,56, z=120,53], EntitySlime['Slime'/101, l='MpServer', x=-6,13, y=5,00, z=139,53], EntitySlime['Slime'/102, l='MpServer', x=-6,13, y=5,00, z=138,31], EntityItem['item.item.carrots'/103, l='MpServer', x=-2,19, y=4,13, z=130,84], EntityVillager['Villager'/105, l='MpServer', x=-4,50, y=4,00, z=143,72], EntityVillager['Villager'/363, l='MpServer', x=11,53, y=5,00, z=172,25], EntitySkeleton['Skeleton'/108, l='MpServer', x=-14,31, y=4,00, z=157,75], EntityVillager['Villager'/364, l='MpServer', x=20,75, y=5,00, z=161,50], EntityBat['Bat'/109, l='MpServer', x=-3,99, y=13,87, z=164,09], EntityVillager['Villager'/365, l='MpServer', x=12,01, y=5,00, z=144,88], EntitySlime['Slime'/366, l='MpServer', x=8,60, y=4,80, z=212,16], EntityBat['Bat'/367, l='MpServer', x=-13,57, y=4,67, z=149,44], EntityVillager['Villager'/368, l='MpServer', x=13,57, y=5,00, z=165,31], EntityBat['Bat'/372, l='MpServer', x=35,44, y=4,67, z=184,22], EntityItem['item.item.potato'/124, l='MpServer', x=1,31, y=5,13, z=122,38], EntityItem['item.item.potato'/125, l='MpServer', x=0,06, y=5,13, z=121,78], EntityVillager['Villager'/126, l='MpServer', x=4,56, y=4,00, z=136,22], EntityItem['item.item.carrots'/127, l='MpServer', x=2,69, y=5,13, z=129,56], EntityClientPlayerMP['iysc'/383, l='MpServer', x=-1,30, y=5,62, z=143,91], EntityItem['item.item.rottenFlesh'/128, l='MpServer', x=4,72, y=4,13, z=140,34], EntityVillager['Villager'/129, l='MpServer', x=8,32, y=4,00, z=145,97], EntityItem['item.item.seeds'/386, l='MpServer', x=-12,81, y=4,13, z=175,78], EntityBat['Bat'/130, l='MpServer', x=27,10, y=15,46, z=148,61], EntityItem['item.item.seeds'/387, l='MpServer', x=-14,06, y=5,13, z=175,03], EntityVillager['Villager'/131, l='MpServer', x=9,60, y=5,00, z=154,97], EntitySlime['Slime'/388, l='MpServer', x=-5,78, y=4,00, z=160,22], EntityVillager['Villager'/132, l='MpServer', x=18,31, y=4,00, z=138,98], EntityItem['item.item.seeds'/133, l='MpServer', x=13,19, y=5,13, z=156,31], EntityItem['item.item.potato'/390, l='MpServer', x=-4,47, y=5,13, z=173,81], EntityItem['item.item.seeds'/134, l='MpServer', x=11,41, y=5,13, z=155,31], EntityItem['item.item.slimeball'/135, l='MpServer', x=12,41, y=4,13, z=153,09], EntitySlime['Slime'/392, l='MpServer', x=-25,38, y=4,00, z=155,63], EntityBat['Bat'/136, l='MpServer', x=0,75, y=7,10, z=154,19], EntitySkeleton['Skeleton'/393, l='MpServer', x=-23,50, y=4,00, z=162,69], EntityVillager['Villager'/137, l='MpServer', x=7,53, y=5,00, z=146,72], EntitySkeleton['Skeleton'/394, l='MpServer', x=-24,38, y=4,00, z=162,50], EntityItem['item.item.rottenFlesh'/138, l='MpServer', x=11,53, y=4,13, z=148,75], EntitySkeleton['Skeleton'/395, l='MpServer', x=-30,00, y=4,00, z=162,69], EntityVillager['Villager'/139, l='MpServer', x=18,59, y=4,00, z=139,74], EntityItem['item.item.arrow'/396, l='MpServer', x=-23,06, y=4,13, z=172,31], EntityVillager['Villager'/140, l='MpServer', x=5,16, y=4,00, z=152,31], EntitySlime['Slime'/397, l='MpServer', x=-14,96, y=4,00, z=156,63], EntityVillager['Villager'/141, l='MpServer', x=21,41, y=4,00, z=147,84], EntityBat['Bat'/398, l='MpServer', x=-10,73, y=4,69, z=148,67], EntityVillager['Villager'/142, l='MpServer', x=13,07, y=5,00, z=156,61], EntityBat['Bat'/399, l='MpServer', x=-1,13, y=8,51, z=149,42], EntityVillager['Villager'/143, l='MpServer', x=3,50, y=4,55, z=154,66], EntityVillager['Villager'/144, l='MpServer', x=10,89, y=5,00, z=143,92], EntityItem['item.item.seeds'/401, l='MpServer', x=-7,25, y=5,13, z=180,81], EntityBat['Bat'/145, l='MpServer', x=-16,56, y=6,11, z=112,39], EntityItem['item.item.wheat'/402, l='MpServer', x=-9,31, y=5,13, z=179,53], EntitySlime['Slime'/403, l='MpServer', x=-78,35, y=4,47, z=176,91], EntityBat['Bat'/404, l='MpServer', x=40,33, y=10,06, z=144,66], EntityBat['Bat'/405, l='MpServer', x=37,39, y=11,22, z=174,58], EntityItem['item.item.tsteelworks.Materials.ScorchedBrick'/149, l='MpServer', x=29,97, y=4,13, z=135,94], EntitySlime['Slime'/406, l='MpServer', x=-6,74, y=4,00, z=189,44], EntitySlime['Slime'/150, l='MpServer', x=18,78, y=4,00, z=134,78], EntitySlime['Slime'/407, l='MpServer', x=-68,28, y=4,00, z=151,13], EntityItem['item.item.slimeball'/152, l='MpServer', x=25,13, y=4,13, z=157,88], EntityItem['item.item.slimeball'/153, l='MpServer', x=25,88, y=4,13, z=159,97], EntityBat['Bat'/154, l='MpServer', x=21,69, y=5,10, z=156,81], EntityItem['item.item.rottenFlesh'/155, l='MpServer', x=18,47, y=4,13, z=148,19], SteelGolem['Steel Golem'/156, l='MpServer', x=24,22, y=4,00, z=148,86], EntityVillager['Villager'/157, l='MpServer', x=20,16, y=4,00, z=152,24], EntitySlime['Slime'/159, l='MpServer', x=40,26, y=4,69, z=116,29], EntityVillager['Villager'/160, l='MpServer', x=2,99, y=5,00, z=156,41], EntitySlime['Slime'/164, l='MpServer', x=27,94, y=10,00, z=161,06], EntityBat['Bat'/165, l='MpServer', x=15,28, y=8,46, z=149,92], EntityBat['Bat'/166, l='MpServer', x=34,30, y=6,96, z=150,65], EntitySlime['Slime'/45478, l='MpServer', x=-17,58, y=4,00, z=182,89], EntityItem['item.item.slimeball'/167, l='MpServer', x=30,75, y=4,13, z=154,75], EntityItem['item.item.slimeball'/168, l='MpServer', x=23,72, y=4,13, z=159,41], EntitySlime['Slime'/57257, l='MpServer', x=18,50, y=9,58, z=146,96], EntitySlime['Slime'/59305, l='MpServer', x=4,38, y=1,00, z=148,34], EntitySlime['Slime'/57258, l='MpServer', x=19,96, y=4,81, z=141,76], EntitySlime['Slime'/59306, l='MpServer', x=5,58, y=1,00, z=148,34], EntitySlime['Slime'/57259, l='MpServer', x=24,22, y=4,00, z=138,34], EntitySlime['Slime'/59307, l='MpServer', x=4,59, y=1,00, z=149,59], EntityItem['item.item.slimeball'/30893, l='MpServer', x=15,97, y=7,13, z=166,19], EntityItem['item.item.slimeball'/30895, l='MpServer', x=11,97, y=7,13, z=167,78], EntitySlime['Slime'/57264, l='MpServer', x=30,03, y=4,14, z=156,56], EntitySlime['Slime'/24765, l='MpServer', x=34,37, y=4,95, z=194,56], EntityItem['item.item.slimeball'/57533, l='MpServer', x=23,78, y=4,13, z=150,25], EntitySlime['Slime'/10431, l='MpServer', x=51,25, y=4,00, z=97,75], EntitySlime['Slime'/194, l='MpServer', x=54,81, y=4,47, z=166,65], EntitySlime['Slime'/195, l='MpServer', x=23,81, y=4,00, z=89,19], EntitySlime['Slime'/196, l='MpServer', x=67,08, y=4,47, z=181,72], EntityBat['Bat'/197, l='MpServer', x=49,22, y=6,76, z=126,88], EntityItem['item.item.slimeball'/58311, l='MpServer', x=23,16, y=4,13, z=157,19], EntityItem['item.item.slimeball'/57290, l='MpServer', x=18,78, y=4,13, z=146,06], EntitySlime['Slime'/13007, l='MpServer', x=32,63, y=4,00, z=157,87], EntityItem['item.item.slimeball'/7891, l='MpServer', x=27,59, y=4,13, z=151,88], EntitySlime['Slime'/17624, l='MpServer', x=2,91, y=4,00, z=169,28], EntityItem['item.item.rottenFlesh'/17113, l='MpServer', x=24,78, y=4,13, z=161,75], EntitySlime['Slime'/17625, l='MpServer', x=-0,75, y=4,00, z=174,78], EntitySlime['Slime'/17626, l='MpServer', x=-15,78, y=4,00, z=133,59], EntitySlime['Slime'/17628, l='MpServer', x=13,12, y=4,02, z=130,47], EntitySlime['Slime'/239, l='MpServer', x=75,50, y=4,31, z=72,64], EntitySlime['Slime'/48883, l='MpServer', x=13,31, y=6,10, z=166,18], EntitySlime['Slime'/56319, l='MpServer', x=30,49, y=4,00, z=154,93]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (x86) version 6.3
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 584072816 bytes (557 MB) / 906809344 bytes (864 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1024m -XX:MaxPermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 69 mods loaded, 69 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1291} [Forge Mod Loader] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1291} [Minecraft Forge] (modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2-core{rv2-beta-8} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10-snapshot-141.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VeinMiner_coremod{null_build-null} [Core mod] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{0.6} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.0RC3} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC3-203.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VoltzEngine{0.3.2} [Voltz Engine] (VoltzEngine-1.7.10-0.3.2b198-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    addictedtored{0.0.1.10} [Addicted To Red] (AddictedToRed-1.7.10-0.0.1b10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv2-beta-8} [Applied Energistics 2] (appliedenergistics2-rv2-beta-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    qmunitylib{1.0} [QmunityLib] (QmunityLib-1.7.10-0.1.92-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bluepower{0.2.892} [Blue Power] (BluePower-1.7.10-0.2.892-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChickenChunks{1.3.4.17} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{2.2.673-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.673-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{9.5.0.0} [Railcraft] (Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{2.3.7.34} [Chisel 2] (Chisel2-2.3.7.34.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.5.27} [EnderStorage] (EnderStorage-1.7.10-1.4.5.27-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalFoundation{1.7.10R1.0.0RC4} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC4-58.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{1.7.10R4.0.0RC3} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0RC3-132.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenComputers{1.5.2.450-dev} [OpenComputers] (OpenComputers-MC1.7.10-1.5.2.450-dev-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.8} [Waila] (Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CompactMachines{1.7.10-1.17} [Compact Machines] (compactmachines-1.7.10-1.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    cookiecore{1.3.1} [Cookie Core] (CookieCore-1.7.10-1.3.1-5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    creationsbt{@VERSION@} [Creations: Builder's Toolkit] (Creations-1.7.10-0.0.1b5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderIO{1.7.10-2.2.8.353} [Ender IO] (EnderIO-1.7.10-2.2.8.353.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderTech{1.7.10-0.3.0.364} [EnderTech] (EnderTech-1.7.10-0.3.0.364.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    extracells{2.2.55} [ExtraCells] (ExtraCells-1.7.10-2.2.55b85.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FastCraft{1.19} [FastCraft] (fastcraft-1.19.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    fastleafdecay{1.0} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    flansmod{4.9.0} [Flan's Mod] (Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    icbm{2.4.0.177} [ICBM] (ICBM-1.7.10-2.4.0b177-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-54.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JABBA{1.2.0b} [JABBA] (Jabba-1.2.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    journeymap{5.0.1} [JourneyMap] (JourneyMap5.0.1_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    madscience{1.11.[NIGHTLY]} [Mad Science] (MadScience-1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mekanism{7.1.2} [Mekanism] (Mekanism-1.7.10-7.1.2.167.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MekanismGenerators{7.1.2} [MekanismGenerators] (MekanismGenerators-1.7.10-7.1.2.167.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MekanismTools{7.1.2} [MekanismTools] (MekanismTools-1.7.10-7.1.2.167.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{0.11.0.00} [Mystcraft] (mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-315.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-566.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    openmodularturrets{1.3.4} [Open Modular Turrets] (OpenModularTurrets-1.7.10-1.3.4-27.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Sampler{1.17} [Sampler] (sampler-1.17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct] (TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TSteelworks{1.7.10-1.1.0} [Tinkers' Steelworks] (TSteelworks-1.7.10-1.1.0-6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ttCore{MC1.7.10-0.1.0-61} [ttCore] (ttCore-MC1.7.10-0.1.0-61.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VeinMiner{0.23.0} [Vein Miner] (VeinMiner-1.7.10_0.23.0.50.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    VeinMinerModSupport{0.23.0} [Mod Support] (VeinMiner-1.7.10_0.23.0.50.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    wailaplugins{MC1.7.10-0.0.1-13} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.0.1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    warpbook{2.0.null} [Warp Book] (warpbook-1.7.10_2.0.36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    yampst{1.3.5} [YAMPST] (Yampst-Voltz-4.0.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    CoFHCore: -[1.7.10]3.0.0RC3-203
    AE2 Version: beta rv2-beta-8 for Forge 10.13.2.1230
    ThermalFoundation: -[1.7.10]1.0.0RC4-58
    ThermalExpansion: -[1.7.10]4.0.0RC3-132
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10-Forge10.13.2.1291
    LWJGL: 2.9.1
    OpenGL: GeForce 9500 GT/PCIe/SSE2/3DNOW! GL version 3.3.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)
```

**Comment by Arzte** [comment]
Do we have git integration with irc?

EDIT: nope
